# Generated by Django 5.0 on 2024-06-27 02:46

import posts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filepost',
            name='file',
            field=models.FileField(upload_to='files/', validators=[posts.models.validate_file_extencion]),
        ),
    ]
